### ISSUE TITLE
Опечатка в KL-дивергенции

### ISSUE THREAD

**Issue by hawkeoni** [FortsAndMills/RL-Theory-book#1]
Добрый день!

Как мне кажется, на странице 32 в пункте 2.2.2 сразу после утверждения 3 в формуле есть ошибка. Первое слагаемое не зависит от лямбды, а зависит только от q(x). Об этом говорится и дальше буквально в следующем предложении.

Исправить это можно предположительно в следующей строчке - https://github.com/FortsAndMills/RL-Theory-book/blob/8d2ab4c1afef7a365af61570a43b0cda60a4d7c5/src/2.MetaHeuristics/2.2.EvolutionStrategies.tex#L55

**Comment by FortsAndMills** [comment]
Вероятно, можно неправильно понять запись const(x). Здесь и далее подразумевается, что слагаемое const(x) есть некоторая функция, которая зависит от x как константа, а то есть не зависит. Видимо, имеет смысл добавить сноску.

**Comment by hawkeoni** [comment]
Возможно, мы говорим о разных вещах. Насколько я вижу в тексте tex-исходников и в pdf-варианте запись не const(x), а const(lambda), что не соответствует действительности. В то же время соглашусь, что запись const(x) подходит.

**Comment by FortsAndMills** [comment]
Добавил туда поясняющую сноску.
