### ISSUE TITLE
Ошибки и опечатки

### ISSUE THREAD

**Issue by nbukhanchenko** [FortsAndMills/RL-Theory-book#11]
1. Абзац 6, страница 18: "В зависимости от скорости работы среды, то есть времени, **_затрачиваемой_** на сбор данных" -> затрачиваемого.
2. Абзац 1, страница 45: "Следовательно, мы, выбрав сейчас то действие a, на **_которых_** достигается максимум" -> котором.
3. Абзац 5, страница 51: "Значит и вся сумма наград будет **_положительна_** для любого стартового состояния" -> неотрицательна.

**Comment by FortsAndMills** [comment]
Благодарю! Поправил всё (в исходниках).
