### ISSUE TITLE
Опечатка в уравнениях Беллмана

### ISSUE THREAD

**Issue by hawkeoni** [FortsAndMills/RL-Theory-book#2]
Добрый день!
В примере 44 на странице 41 расписаны уравнения Беллмана. В предпоследнем уравнении V^{pi}(B) в последней скобке есть слагаемое \gamma * V^{pi}(C). Кажется, что вместо него должно было находиться терминальное состояние, т.е. \gamma * 0.

**Comment by hawkeoni** [comment]
Также в примере 46 дублируется Q(s=B, a=blue) дважды, должно быть Q(s=C...)

**Comment by FortsAndMills** [comment]
fixed
