### ISSUE TITLE
Опечатки

### ISSUE THREAD

**Issue by mrph2898** [FortsAndMills/RL-Theory-book#5]
До главы 3:
Стр. 20, вторая строка "...проблему наши алгоритм**А** обучения..."
Стр. 21, пример "В общем случае MDP, заданн**ое**" --> -ый
Стр. 23, определение мета-эвристики, в английском названии, кажется, лишние буквы: "stochastic zero**th**-order"
Стр. 23, после определения, 2 абзац, "В теории мета-эвристик опция «**запросить оракул** в одной и той же точке
несколько раз»". Что имеется в виду под запросить оракул? Может "запросить оракула значение"?
Стр. 27, орешек под графиком: "отвечающий за «силу мутаций», например дисперсия σ гауссовского шума в примере 33, а то есть тоже связанный ...". Запятая после "например", и непонятно выражение "а то есть"
Стр. 27, самое начало параграфа про эволюционные алгоритмы: "**Нам**, вообще говоря, на очередном
шаге **нам** доступна", нам
Стр. 29, Пример 36 с топологической мутацией: "и выход одного **подаётся добавляется** к входу", что-то одно лишнее
Стр. 29, второй абзац в Видовой специализации: "...выживать особям, оказавшихся в не исследующихся местах...", придирка, но "в не исследуемых местах" звучит лучше
Стр. 32, Оценка вероятности редкого события, второй абзац: "Под словами «редкое событие» подразумевается, что **выражение в индикаторе не равно нулю** с вероятностью, крайне близкой к нулю.". Имелось в виду, что сам индикатор этого выражения равен единице (не равен нулю) с малой вероятностью?
Стр. 34, абзац перед 2.2.4: "...Поскольку некоторая доля плохих точек было выкинуто из выборки..." - "доля ... была выкинута"
Стр. 38, последний абзац: "Если мы попробуем проделать с данным подходом (оптимизацией (2.5)) проделать тот" - проделать

**Comment by mrph2898** [comment]
Параграф 3.1:
3.1.1., первый абзац, "ограничения: марковость и ста**нц**ионарность"
3.1.6., Первое в пункте утверждение с неравенством, последний переход с переносом. Знак равно на предыдущей строке вместо \leq
3.1.7. Утверждение 15, формально, в формулировке теоремы ещё надо указать, что для любого действия
3.1.10. Теорема Критерий оптимальности Беллмана. В достаточности после подстановки QQ должны быть везде штрихи над состояниями и действиями (во втором переходе их нет)

**Comment by FortsAndMills** [comment]
БОЛЬШОЕ СПАСИБО!

P.S. Если что, там из главы 2 в курсе был только Кросс-энтропийный метод (CEM), поэтому остальное можно было не читать =D

**Comment by mrph2898** [comment]
> БОЛЬШОЕ СПАСИБО!
> 
> P.S. Если что, там из главы 2 в курсе был только Кросс-энтропийный метод (CEM), поэтому остальное можно было не читать =D

Уже прочитал всё, интересно же) 
Я линейно иду (бандитов, может, только не посмотрю до экзамена)), если буду ещё находить опечатки, сюда запишу

**Comment by mrph2898** [comment]
Параграф 3.2
3.2.1, второй абзац: "мы засэмплировали из траекторию s; a; s0; a0;" - "из" лишнее?
3.2.1, стр.50, третий абзац: "Так, если Qπ(s; a) = V π(s), то мы можем заключить, что выбор a не привёл ни к какой награде, которую мы не ожидаем в состоянии s. Если, например, r(s; a) + V π(s0) > Qπ(s; a)..." - 
В первом предложении стоит, возможно, сказать, что для фиксированного состояния? Во втором ясно, что цель подвести к advantage разнице, но ведь правильнее сравнивать с r + \gamma V(s`), может, как-то по-другому здесь надо описать?
3.2.3. Рассуждения после теоремы: "Если эта нижняя оценка поднята выше V π1(s; a), то стратегию" - V^{\pi_1}(s) без действия
3.2.4. Беда с нумерациями сносок (внутри теоремы и за её пределами имеет один и тот же номер и он неправильный (возможно, после перекомпиляции оно исчезло))). 

Параграф 3.3
3.3.1. В теореме Банаха тоже поехал номер сноски. И далее в 3.3.2, причём неясно, к чему привязана нумерация - ни к  параграфу, ни к пункту. Может, я и до этого не замечал, но думал, что привязаны к странице номера (в основном, так и было)
3.3.3. Утверждение 25. В доказательстве первый переход должен быть равенством, там же x^{*} точный максимум
3.3.5. Почти конец, стр.61, "в таким ситуациях"

Параграф 3.4
3.4.1. Утверждение 31, не уверен, но ранее, вроде, не использовался термин learning rate. Понятно, что это alpha, по аналогии с SGD, но можно просто написать именно alpha_k (только в след. пункте явно прописано, почему так можно назвать)
3.4.8. стр. 72, после утверждения 34, "Мы могли бы, вообще говоря**ть**,"
3.4.8. стр.73, последний абзац, "Чтобы понять, что это влечёт", лучше - "Чтобы понять, к чему это приводит,"

Параграф 3.5
***Ещё не до конца прошёлся***

Параграф 4.1
4.1.2. стр.87, в несмещённой оценке градиента нет закрывающей скобки (формула 4.2)
Далее, теорема: "...семейством, **а** то есть табличкой" - лишнее?
4.1.3. первый абзац: ", то есть фиксирова**нн**ию задачи регрессии."
стр.88 "может **стать** немножко «сломаться»" - лишнее слово

Параграф 4.2
4.2.5. конец первого абзаца: "головой об стенкой"
4.2.8. Нужно ли в формуле с \ Psi^{Retrace} в верхнем индексе произведения писать "i = "?

Параграф 4.3
4.3.1. третий абзац, " оговориться о противоречиях, связанн**ой** с" - ых
4.3.4. опр.66, 67, нумерация сносок совпадает, та же проблема, что и раньше(
4.3.6. опр.69, "p — набор из 51 числа, суммирующихся в единицу". Ясно, что дальше пойдёт C51, но в определении явно задаётся же индексация для p_i и заводится переменная под количество атомов

(по policy gradient тоже сделаю))

**Comment by FortsAndMills** [comment]
Снова спасибо! Всё поправил (пока только в исходниках).

**Comment by mrph2898** [comment]
Параграф 5.1
5.1.2. Везде кажется, что должно быть V^{\pi_{\theta}}(s_0) вместо V^{\pi_{\theta}}(s).
Также утверждение 51, после самого последнего перехода сумма по t=0 -> t\geq0
5.1.3. орешек после утв.52, "можно считать неко**е**й"
5.1.5. второй абзац после опр.73. "марковская цепь уже «разгорелась»" - может, всё же, "разогрелась" (хотя так тоже красиво ~~горит~~ звучит)?))
5.1.7. стр.129, единственная формула на странице, максимизация по \pi_{\theta} или по \theta должна быть, а не просто \pi

Параграф 7.2
7.2.1. теорема 81, "что **для** a0 неоптимально " возможно, "для"лишнее

Параграф 7.3
7.3.5. сноска 9, "ряд неприн**и**ципиальных" - лишнее

Параграф 7.4
7.4.4. стр.187, абзац после формул приближения, "в этой рассматриваемой задач**и** мы" -че

Параграф 8.1
8.1.1. Пример DAgger, "собрать набор **тот** состояний"
8.1.2. Первый абзац (почему-то сейчас решил указать на запятую)), "На самом деле в разных " - перед "в"
Ладненько, ещё пример 114 "Допустим для простоты, мы также знаем" - лишняя перед "мы", не хватает перед "для"
Далее "Что мы тогда можем о ней, имея на" - "о ней **сказать**", наверное
8.1.4. В формуле 8.17 перед энтропией с крышечкой должен быть минус (из доказательства следует, кажется)

**Comment by mrph2898** [comment]
Остальные параграфы после экзамена уже))

**Comment by mrph2898** [comment]
Параграф 5.2
5.2.1. Орешек: "Можно ли мы " - можем

**Comment by FortsAndMills** [comment]
Снова огромное спасибо! Очень благодарен! Всё поправил, включая запятые!

**Comment by iject** [comment]
Стр. 43: "Вдруг в одних s **макисмум** (3.4) достигается на одной стратегии, а в другом на другой?" — максимум
Стр. 66: "Вы прикидываете, что в среднем **этой** займёт −Q(s, a) = 30 минут." — это

Спасибо большое за вашу работу!
