### ISSUE TITLE
Указание на формулу до её введения

### ISSUE THREAD

**Issue by CrafterKolyan** [FortsAndMills/RL-Theory-book#6]
5.1.6. Расцепление внешней и внутренней стохастики
Итак, давайте попробуем формально понять, из какого распределения приходят состояния в формуле градиента (**5.12**), и отличается ли оно от µπ(s). Для этого мы сейчас придумаем, как можно записывать функционалы
вида

Кажется, что там должна быть не **5.12**, а наверное **5.7**, но вообще точно я сказать не могу какая формула имеется в виду.

**Comment by FortsAndMills** [comment]
Да, ссылка должна была быть на формулу градиента в общем виде (5.4), а не в будущее, конечно.
