### ISSUE TITLE
Кажется что ошибка в главе 6

### ISSUE THREAD

**Issue by nor-code** [FortsAndMills/RL-Theory-book#9]
Там, где описывается полный алгоритм DDPG (в рамочке) https://github.com/FortsAndMills/RL-Theory-book/blob/main/src/6.ContinuousControl/6.1.DDPG.tex , то там такое условие, что если  ```t mod K == 0```то обновляем веса актора и критика по формуле скользящего среднего, но такого нет в оригинальной статье https://arxiv.org/pdf/1509.02971.pdf (стр. 5), там просто на каждом шаге происходит обновление.

**Comment by FortsAndMills** [comment]
Да, и к тому же гиперпараметр K не определён. Это, конечно, опечатка.
